# Generated by Django 6.1 on 2026-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
