# Generated by Django 6.1 on 2026-09-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='محصول ویژه (نمایش در صفحه اصلی)'),
        ),
    ]
